//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionExistence
    {
        public int Id { get; set; }
        public Nullable<int> PageNameId { get; set; }
        public Nullable<int> ActionNameId { get; set; }
        public Nullable<bool> IsExist { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ActionName ActionName { get; set; }
        public virtual PageName PageName { get; set; }
    }
}
