//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartonMgmtStockTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartonMgmtStockTransfer()
        {
            this.CartonMgmtDetailsStockTransfers = new HashSet<CartonMgmtDetailsStockTransfer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DistributionSummaryID { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<System.DateTime> PackDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> FromBranchID { get; set; }
        public Nullable<int> ToBranchID { get; set; }
        public string IBTNumber { get; set; }
        public Nullable<int> CartonNumber { get; set; }
        public Nullable<bool> IsDispatched { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartonMgmtDetailsStockTransfer> CartonMgmtDetailsStockTransfers { get; set; }
        public virtual StockDistributionSummary StockDistributionSummary { get; set; }
    }
}
