//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountSummary()
        {
            this.PromotionalDiscounts = new HashSet<PromotionalDiscount>();
        }
    
        public int Id { get; set; }
        public string FromProductSKU { get; set; }
        public string ToProductSKU { get; set; }
        public string FromStyleSKU { get; set; }
        public string ToStyleSKU { get; set; }
        public string FromPrice { get; set; }
        public string ToPrice { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public string DiscountType { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionalDiscount> PromotionalDiscounts { get; set; }
    }
}
