//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Image1 { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
