//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayBaySale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LayBaySale()
        {
            this.ReleaseLayBayItems = new HashSet<ReleaseLayBayItem>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string LayBayNo { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<decimal> InitValue { get; set; }
        public Nullable<decimal> CountValue { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> DepositeAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseLayBayItem> ReleaseLayBayItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
