//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ActionLogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PageId { get; set; }
        public string LogTable { get; set; }
    
        public virtual ActionLog ActionLog { get; set; }
        public virtual PageName PageName { get; set; }
        public virtual User User { get; set; }
    }
}
