//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkDown
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarkDown()
        {
            this.MarkDownBranches = new HashSet<MarkDownBranch>();
        }
    
        public int Id { get; set; }
        public string ProductSKU { get; set; }
        public string StyleSKU { get; set; }
        public Nullable<decimal> OriginalSellingPrice { get; set; }
        public Nullable<int> PercentageDecrease { get; set; }
        public Nullable<bool> IsPercentageOriginalPrice { get; set; }
        public Nullable<decimal> NewSellingPrice { get; set; }
        public Nullable<decimal> NewCashPrice { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkDownBranch> MarkDownBranches { get; set; }
    }
}
