//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartonManagementDetails = new HashSet<CartonManagementDetail>();
            this.CartonMgmtDetailsStockTransfers = new HashSet<CartonMgmtDetailsStockTransfer>();
            this.IBTDetails = new HashSet<IBTDetail>();
            this.PendingItemReceipts = new HashSet<PendingItemReceipt>();
            this.PromotionalDiscounts = new HashSet<PromotionalDiscount>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.ReceiptOrderItems = new HashSet<ReceiptOrderItem>();
            this.ReleaseLayBayItems = new HashSet<ReleaseLayBayItem>();
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
            this.StockBranchInventories = new HashSet<StockBranchInventory>();
            this.StockDistributions = new HashSet<StockDistribution>();
            this.StockInventories = new HashSet<StockInventory>();
            this.StockSupplierTransactions = new HashSet<StockSupplierTransaction>();
            this.StockTapes = new HashSet<StockTape>();
            this.StockWarehouseTransactions = new HashSet<StockWarehouseTransaction>();
        }
    
        public int Id { get; set; }
        public string ProductSKU { get; set; }
        public string StyleSKU { get; set; }
        public string LongDescription { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> SizeGridID { get; set; }
        public Nullable<decimal> RecommendedSellingPrice { get; set; }
        public Nullable<decimal> ActualSellingPrice { get; set; }
        public Nullable<bool> IsVPI { get; set; }
        public Nullable<bool> IsMarkDown { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> ProductSourceID { get; set; }
        public string SupplierStyle { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<decimal> CostPriceUSD { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<bool> IsAllowZero { get; set; }
        public Nullable<int> DefaultTemplateID { get; set; }
        public Nullable<int> MarkDownTemplateID { get; set; }
        public string IsFreeGift { get; set; }
        public Nullable<bool> IsConsignment { get; set; }
        public Nullable<bool> IsDiscontinue { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PrimaryImage { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string AvailableSize { get; set; }
        public Nullable<int> LogId { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> ProdCat1ID { get; set; }
        public Nullable<int> ProdCat2ID { get; set; }
        public Nullable<int> ProdCat3ID { get; set; }
        public Nullable<int> ProdCat4ID { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartonManagementDetail> CartonManagementDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartonMgmtDetailsStockTransfer> CartonMgmtDetailsStockTransfers { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IBTDetail> IBTDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingItemReceipt> PendingItemReceipts { get; set; }
        public virtual ProductCat1 ProductCat1 { get; set; }
        public virtual ProductCat2 ProductCat2 { get; set; }
        public virtual ProductCat3 ProductCat3 { get; set; }
        public virtual ProductCat4 ProductCat4 { get; set; }
        public virtual ProductSource ProductSource { get; set; }
        public virtual Season Season { get; set; }
        public virtual SizeGrid SizeGrid { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Template Template { get; set; }
        public virtual Template Template1 { get; set; }
        public virtual Year Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionalDiscount> PromotionalDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptOrderItem> ReceiptOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseLayBayItem> ReleaseLayBayItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockBranchInventory> StockBranchInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDistribution> StockDistributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInventory> StockInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockSupplierTransaction> StockSupplierTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTape> StockTapes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockWarehouseTransaction> StockWarehouseTransactions { get; set; }
    }
}
