//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionalDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromotionalDiscount()
        {
            this.DiscountBranches = new HashSet<DiscountBranch>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> DiscountSummaryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountBranch> DiscountBranches { get; set; }
        public virtual DiscountSummary DiscountSummary { get; set; }
        public virtual Product Product { get; set; }
    }
}
