//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiveOrder()
        {
            this.PendingItemReceipts = new HashSet<PendingItemReceipt>();
            this.ReceiptOrderItems = new HashSet<ReceiptOrderItem>();
        }
    
        public int Id { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalVAT { get; set; }
        public string SupplierInvoice { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<bool> ReceiptStatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<bool> IsFinalize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingItemReceipt> PendingItemReceipts { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptOrderItem> ReceiptOrderItems { get; set; }
    }
}
