//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseLayBayItem
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> ProductSize { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> LayBayId { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
    
        public virtual LayBaySale LayBaySale { get; set; }
        public virtual Product Product { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
