//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.ReleaseLayBayItems = new HashSet<ReleaseLayBayItem>();
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SalesId { get; set; }
        public string OrderNumber { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public string SaleType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public byte[] PromoCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> PacketQuantity { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseLayBayItem> ReleaseLayBayItems { get; set; }
        public virtual StaffMember StaffMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
