//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.SalesTransactions = new HashSet<SalesTransaction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<int> LayBayId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMode { get; set; }
        public string SalesType { get; set; }
        public Nullable<byte> IsCreditNoteRedeemed { get; set; }
        public string CreditNoteNumber { get; set; }
        public Nullable<int> CashierId { get; set; }
        public Nullable<decimal> AmountTendered { get; set; }
        public string Change { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LayBaySale LayBaySale { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTransaction> SalesTransactions { get; set; }
        public virtual StaffMember StaffMember { get; set; }
    }
}
