//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RemainingStockByBranchByProduct
    {
        public Nullable<int> BranchID { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
    }
}
