//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount()
        {
            this.BranchDiscounts = new HashSet<BranchDiscount>();
        }
    
        public int Id { get; set; }
        public string ProductSKU { get; set; }
        public string StyleSKU { get; set; }
        public Nullable<bool> IsFlatDiscount { get; set; }
        public Nullable<bool> IsQuantityDiscount { get; set; }
        public string MinimumQuantity { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string PercentDiscount { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchDiscount> BranchDiscounts { get; set; }
    }
}
